// Kyber NTT Twiddle Factor ROM
// Auto-generated by gen_twiddle_factors.py
// Parameters: n=256, q=3329, zeta=17

module twiddle_rom #(
    parameter DATA_WIDTH = 12,
    parameter ADDR_WIDTH = 8
)(
    input  wire                      clk,
    input  wire [ADDR_WIDTH-1:0]     addr_forward,
    input  wire [ADDR_WIDTH-1:0]     addr_backward,
    input  wire [6:0]                addr_pwm,
    output reg  [DATA_WIDTH-1:0]     data_forward,
    output reg  [DATA_WIDTH-1:0]     data_backward,
    output reg  [DATA_WIDTH-1:0]     data_pwm
);

    // Forward NTT twiddle factors (bit-reversed order)
    reg [DATA_WIDTH-1:0] rom_forward [0:255];
    
    // Backward INTT twiddle factors (bit-reversed order)
    reg [DATA_WIDTH-1:0] rom_backward [0:255];
    
    // PWM twiddle factors (zeta^(2*br(i)+1))
    reg [DATA_WIDTH-1:0] rom_pwm [0:127];
    
    // Initialize ROMs
    initial begin
        // Forward NTT twiddles
rom_forward[  0] = 12'd   1; rom_forward[  1] = 12'd3328; rom_forward[  2] = 12'd1729; rom_forward[  3] = 12'd1600; rom_forward[  4] = 12'd2580; rom_forward[  5] = 12'd 749; rom_forward[  6] = 12'd3289; rom_forward[  7] = 12'd  40; 
rom_forward[  8] = 12'd2642; rom_forward[  9] = 12'd 687; rom_forward[ 10] = 12'd 630; rom_forward[ 11] = 12'd2699; rom_forward[ 12] = 12'd1897; rom_forward[ 13] = 12'd1432; rom_forward[ 14] = 12'd 848; rom_forward[ 15] = 12'd2481; 
rom_forward[ 16] = 12'd1062; rom_forward[ 17] = 12'd2267; rom_forward[ 18] = 12'd1919; rom_forward[ 19] = 12'd1410; rom_forward[ 20] = 12'd 193; rom_forward[ 21] = 12'd3136; rom_forward[ 22] = 12'd 797; rom_forward[ 23] = 12'd2532; 
rom_forward[ 24] = 12'd2786; rom_forward[ 25] = 12'd 543; rom_forward[ 26] = 12'd3260; rom_forward[ 27] = 12'd  69; rom_forward[ 28] = 12'd 569; rom_forward[ 29] = 12'd2760; rom_forward[ 30] = 12'd1746; rom_forward[ 31] = 12'd1583; 
rom_forward[ 32] = 12'd 296; rom_forward[ 33] = 12'd3033; rom_forward[ 34] = 12'd2447; rom_forward[ 35] = 12'd 882; rom_forward[ 36] = 12'd1339; rom_forward[ 37] = 12'd1990; rom_forward[ 38] = 12'd1476; rom_forward[ 39] = 12'd1853; 
rom_forward[ 40] = 12'd3046; rom_forward[ 41] = 12'd 283; rom_forward[ 42] = 12'd  56; rom_forward[ 43] = 12'd3273; rom_forward[ 44] = 12'd2240; rom_forward[ 45] = 12'd1089; rom_forward[ 46] = 12'd1333; rom_forward[ 47] = 12'd1996; 
rom_forward[ 48] = 12'd1426; rom_forward[ 49] = 12'd1903; rom_forward[ 50] = 12'd2094; rom_forward[ 51] = 12'd1235; rom_forward[ 52] = 12'd 535; rom_forward[ 53] = 12'd2794; rom_forward[ 54] = 12'd2882; rom_forward[ 55] = 12'd 447; 
rom_forward[ 56] = 12'd2393; rom_forward[ 57] = 12'd 936; rom_forward[ 58] = 12'd2879; rom_forward[ 59] = 12'd 450; rom_forward[ 60] = 12'd1974; rom_forward[ 61] = 12'd1355; rom_forward[ 62] = 12'd 821; rom_forward[ 63] = 12'd2508; 
rom_forward[ 64] = 12'd 289; rom_forward[ 65] = 12'd3040; rom_forward[ 66] = 12'd 331; rom_forward[ 67] = 12'd2998; rom_forward[ 68] = 12'd3253; rom_forward[ 69] = 12'd  76; rom_forward[ 70] = 12'd1756; rom_forward[ 71] = 12'd1573; 
rom_forward[ 72] = 12'd1197; rom_forward[ 73] = 12'd2132; rom_forward[ 74] = 12'd2304; rom_forward[ 75] = 12'd1025; rom_forward[ 76] = 12'd2277; rom_forward[ 77] = 12'd1052; rom_forward[ 78] = 12'd2055; rom_forward[ 79] = 12'd1274; 
rom_forward[ 80] = 12'd 650; rom_forward[ 81] = 12'd2679; rom_forward[ 82] = 12'd1977; rom_forward[ 83] = 12'd1352; rom_forward[ 84] = 12'd2513; rom_forward[ 85] = 12'd 816; rom_forward[ 86] = 12'd 632; rom_forward[ 87] = 12'd2697; 
rom_forward[ 88] = 12'd2865; rom_forward[ 89] = 12'd 464; rom_forward[ 90] = 12'd  33; rom_forward[ 91] = 12'd3296; rom_forward[ 92] = 12'd1320; rom_forward[ 93] = 12'd2009; rom_forward[ 94] = 12'd1915; rom_forward[ 95] = 12'd1414; 
rom_forward[ 96] = 12'd2319; rom_forward[ 97] = 12'd1010; rom_forward[ 98] = 12'd1435; rom_forward[ 99] = 12'd1894; rom_forward[100] = 12'd 807; rom_forward[101] = 12'd2522; rom_forward[102] = 12'd 452; rom_forward[103] = 12'd2877; 
rom_forward[104] = 12'd1438; rom_forward[105] = 12'd1891; rom_forward[106] = 12'd2868; rom_forward[107] = 12'd 461; rom_forward[108] = 12'd1534; rom_forward[109] = 12'd1795; rom_forward[110] = 12'd2402; rom_forward[111] = 12'd 927; 
rom_forward[112] = 12'd2647; rom_forward[113] = 12'd 682; rom_forward[114] = 12'd2617; rom_forward[115] = 12'd 712; rom_forward[116] = 12'd1481; rom_forward[117] = 12'd1848; rom_forward[118] = 12'd 648; rom_forward[119] = 12'd2681; 
rom_forward[120] = 12'd2474; rom_forward[121] = 12'd 855; rom_forward[122] = 12'd3110; rom_forward[123] = 12'd 219; rom_forward[124] = 12'd1227; rom_forward[125] = 12'd2102; rom_forward[126] = 12'd 910; rom_forward[127] = 12'd2419; 
rom_forward[128] = 12'd  17; rom_forward[129] = 12'd3312; rom_forward[130] = 12'd2761; rom_forward[131] = 12'd 568; rom_forward[132] = 12'd 583; rom_forward[133] = 12'd2746; rom_forward[134] = 12'd2649; rom_forward[135] = 12'd 680; 
rom_forward[136] = 12'd1637; rom_forward[137] = 12'd1692; rom_forward[138] = 12'd 723; rom_forward[139] = 12'd2606; rom_forward[140] = 12'd2288; rom_forward[141] = 12'd1041; rom_forward[142] = 12'd1100; rom_forward[143] = 12'd2229; 
rom_forward[144] = 12'd1409; rom_forward[145] = 12'd1920; rom_forward[146] = 12'd2662; rom_forward[147] = 12'd 667; rom_forward[148] = 12'd3281; rom_forward[149] = 12'd  48; rom_forward[150] = 12'd 233; rom_forward[151] = 12'd3096; 
rom_forward[152] = 12'd 756; rom_forward[153] = 12'd2573; rom_forward[154] = 12'd2156; rom_forward[155] = 12'd1173; rom_forward[156] = 12'd3015; rom_forward[157] = 12'd 314; rom_forward[158] = 12'd3050; rom_forward[159] = 12'd 279; 
rom_forward[160] = 12'd1703; rom_forward[161] = 12'd1626; rom_forward[162] = 12'd1651; rom_forward[163] = 12'd1678; rom_forward[164] = 12'd2789; rom_forward[165] = 12'd 540; rom_forward[166] = 12'd1789; rom_forward[167] = 12'd1540; 
rom_forward[168] = 12'd1847; rom_forward[169] = 12'd1482; rom_forward[170] = 12'd 952; rom_forward[171] = 12'd2377; rom_forward[172] = 12'd1461; rom_forward[173] = 12'd1868; rom_forward[174] = 12'd2687; rom_forward[175] = 12'd 642; 
rom_forward[176] = 12'd 939; rom_forward[177] = 12'd2390; rom_forward[178] = 12'd2308; rom_forward[179] = 12'd1021; rom_forward[180] = 12'd2437; rom_forward[181] = 12'd 892; rom_forward[182] = 12'd2388; rom_forward[183] = 12'd 941; 
rom_forward[184] = 12'd 733; rom_forward[185] = 12'd2596; rom_forward[186] = 12'd2337; rom_forward[187] = 12'd 992; rom_forward[188] = 12'd 268; rom_forward[189] = 12'd3061; rom_forward[190] = 12'd 641; rom_forward[191] = 12'd2688; 
rom_forward[192] = 12'd1584; rom_forward[193] = 12'd1745; rom_forward[194] = 12'd2298; rom_forward[195] = 12'd1031; rom_forward[196] = 12'd2037; rom_forward[197] = 12'd1292; rom_forward[198] = 12'd3220; rom_forward[199] = 12'd 109; 
rom_forward[200] = 12'd 375; rom_forward[201] = 12'd2954; rom_forward[202] = 12'd2549; rom_forward[203] = 12'd 780; rom_forward[204] = 12'd2090; rom_forward[205] = 12'd1239; rom_forward[206] = 12'd1645; rom_forward[207] = 12'd1684; 
rom_forward[208] = 12'd1063; rom_forward[209] = 12'd2266; rom_forward[210] = 12'd 319; rom_forward[211] = 12'd3010; rom_forward[212] = 12'd2773; rom_forward[213] = 12'd 556; rom_forward[214] = 12'd 757; rom_forward[215] = 12'd2572; 
rom_forward[216] = 12'd2099; rom_forward[217] = 12'd1230; rom_forward[218] = 12'd 561; rom_forward[219] = 12'd2768; rom_forward[220] = 12'd2466; rom_forward[221] = 12'd 863; rom_forward[222] = 12'd2594; rom_forward[223] = 12'd 735; 
rom_forward[224] = 12'd2804; rom_forward[225] = 12'd 525; rom_forward[226] = 12'd1092; rom_forward[227] = 12'd2237; rom_forward[228] = 12'd 403; rom_forward[229] = 12'd2926; rom_forward[230] = 12'd1026; rom_forward[231] = 12'd2303; 
rom_forward[232] = 12'd1143; rom_forward[233] = 12'd2186; rom_forward[234] = 12'd2150; rom_forward[235] = 12'd1179; rom_forward[236] = 12'd2775; rom_forward[237] = 12'd 554; rom_forward[238] = 12'd 886; rom_forward[239] = 12'd2443; 
rom_forward[240] = 12'd1722; rom_forward[241] = 12'd1607; rom_forward[242] = 12'd1212; rom_forward[243] = 12'd2117; rom_forward[244] = 12'd1874; rom_forward[245] = 12'd1455; rom_forward[246] = 12'd1029; rom_forward[247] = 12'd2300; 
rom_forward[248] = 12'd2110; rom_forward[249] = 12'd1219; rom_forward[250] = 12'd2935; rom_forward[251] = 12'd 394; rom_forward[252] = 12'd 885; rom_forward[253] = 12'd2444; rom_forward[254] = 12'd2154; rom_forward[255] = 12'd1175; 

        // Backward INTT twiddles
rom_backward[  0] = 12'd   1; rom_backward[  1] = 12'd3328; rom_backward[  2] = 12'd1600; rom_backward[  3] = 12'd1729; rom_backward[  4] = 12'd  40; rom_backward[  5] = 12'd3289; rom_backward[  6] = 12'd 749; rom_backward[  7] = 12'd2580; 
rom_backward[  8] = 12'd2481; rom_backward[  9] = 12'd 848; rom_backward[ 10] = 12'd1432; rom_backward[ 11] = 12'd1897; rom_backward[ 12] = 12'd2699; rom_backward[ 13] = 12'd 630; rom_backward[ 14] = 12'd 687; rom_backward[ 15] = 12'd2642; 
rom_backward[ 16] = 12'd1583; rom_backward[ 17] = 12'd1746; rom_backward[ 18] = 12'd2760; rom_backward[ 19] = 12'd 569; rom_backward[ 20] = 12'd  69; rom_backward[ 21] = 12'd3260; rom_backward[ 22] = 12'd 543; rom_backward[ 23] = 12'd2786; 
rom_backward[ 24] = 12'd2532; rom_backward[ 25] = 12'd 797; rom_backward[ 26] = 12'd3136; rom_backward[ 27] = 12'd 193; rom_backward[ 28] = 12'd1410; rom_backward[ 29] = 12'd1919; rom_backward[ 30] = 12'd2267; rom_backward[ 31] = 12'd1062; 
rom_backward[ 32] = 12'd2508; rom_backward[ 33] = 12'd 821; rom_backward[ 34] = 12'd1355; rom_backward[ 35] = 12'd1974; rom_backward[ 36] = 12'd 450; rom_backward[ 37] = 12'd2879; rom_backward[ 38] = 12'd 936; rom_backward[ 39] = 12'd2393; 
rom_backward[ 40] = 12'd 447; rom_backward[ 41] = 12'd2882; rom_backward[ 42] = 12'd2794; rom_backward[ 43] = 12'd 535; rom_backward[ 44] = 12'd1235; rom_backward[ 45] = 12'd2094; rom_backward[ 46] = 12'd1903; rom_backward[ 47] = 12'd1426; 
rom_backward[ 48] = 12'd1996; rom_backward[ 49] = 12'd1333; rom_backward[ 50] = 12'd1089; rom_backward[ 51] = 12'd2240; rom_backward[ 52] = 12'd3273; rom_backward[ 53] = 12'd  56; rom_backward[ 54] = 12'd 283; rom_backward[ 55] = 12'd3046; 
rom_backward[ 56] = 12'd1853; rom_backward[ 57] = 12'd1476; rom_backward[ 58] = 12'd1990; rom_backward[ 59] = 12'd1339; rom_backward[ 60] = 12'd 882; rom_backward[ 61] = 12'd2447; rom_backward[ 62] = 12'd3033; rom_backward[ 63] = 12'd 296; 
rom_backward[ 64] = 12'd2419; rom_backward[ 65] = 12'd 910; rom_backward[ 66] = 12'd2102; rom_backward[ 67] = 12'd1227; rom_backward[ 68] = 12'd 219; rom_backward[ 69] = 12'd3110; rom_backward[ 70] = 12'd 855; rom_backward[ 71] = 12'd2474; 
rom_backward[ 72] = 12'd2681; rom_backward[ 73] = 12'd 648; rom_backward[ 74] = 12'd1848; rom_backward[ 75] = 12'd1481; rom_backward[ 76] = 12'd 712; rom_backward[ 77] = 12'd2617; rom_backward[ 78] = 12'd 682; rom_backward[ 79] = 12'd2647; 
rom_backward[ 80] = 12'd 927; rom_backward[ 81] = 12'd2402; rom_backward[ 82] = 12'd1795; rom_backward[ 83] = 12'd1534; rom_backward[ 84] = 12'd 461; rom_backward[ 85] = 12'd2868; rom_backward[ 86] = 12'd1891; rom_backward[ 87] = 12'd1438; 
rom_backward[ 88] = 12'd2877; rom_backward[ 89] = 12'd 452; rom_backward[ 90] = 12'd2522; rom_backward[ 91] = 12'd 807; rom_backward[ 92] = 12'd1894; rom_backward[ 93] = 12'd1435; rom_backward[ 94] = 12'd1010; rom_backward[ 95] = 12'd2319; 
rom_backward[ 96] = 12'd1414; rom_backward[ 97] = 12'd1915; rom_backward[ 98] = 12'd2009; rom_backward[ 99] = 12'd1320; rom_backward[100] = 12'd3296; rom_backward[101] = 12'd  33; rom_backward[102] = 12'd 464; rom_backward[103] = 12'd2865; 
rom_backward[104] = 12'd2697; rom_backward[105] = 12'd 632; rom_backward[106] = 12'd 816; rom_backward[107] = 12'd2513; rom_backward[108] = 12'd1352; rom_backward[109] = 12'd1977; rom_backward[110] = 12'd2679; rom_backward[111] = 12'd 650; 
rom_backward[112] = 12'd1274; rom_backward[113] = 12'd2055; rom_backward[114] = 12'd1052; rom_backward[115] = 12'd2277; rom_backward[116] = 12'd1025; rom_backward[117] = 12'd2304; rom_backward[118] = 12'd2132; rom_backward[119] = 12'd1197; 
rom_backward[120] = 12'd1573; rom_backward[121] = 12'd1756; rom_backward[122] = 12'd  76; rom_backward[123] = 12'd3253; rom_backward[124] = 12'd2998; rom_backward[125] = 12'd 331; rom_backward[126] = 12'd3040; rom_backward[127] = 12'd 289; 
rom_backward[128] = 12'd1175; rom_backward[129] = 12'd2154; rom_backward[130] = 12'd2444; rom_backward[131] = 12'd 885; rom_backward[132] = 12'd 394; rom_backward[133] = 12'd2935; rom_backward[134] = 12'd1219; rom_backward[135] = 12'd2110; 
rom_backward[136] = 12'd2300; rom_backward[137] = 12'd1029; rom_backward[138] = 12'd1455; rom_backward[139] = 12'd1874; rom_backward[140] = 12'd2117; rom_backward[141] = 12'd1212; rom_backward[142] = 12'd1607; rom_backward[143] = 12'd1722; 
rom_backward[144] = 12'd2443; rom_backward[145] = 12'd 886; rom_backward[146] = 12'd 554; rom_backward[147] = 12'd2775; rom_backward[148] = 12'd1179; rom_backward[149] = 12'd2150; rom_backward[150] = 12'd2186; rom_backward[151] = 12'd1143; 
rom_backward[152] = 12'd2303; rom_backward[153] = 12'd1026; rom_backward[154] = 12'd2926; rom_backward[155] = 12'd 403; rom_backward[156] = 12'd2237; rom_backward[157] = 12'd1092; rom_backward[158] = 12'd 525; rom_backward[159] = 12'd2804; 
rom_backward[160] = 12'd 735; rom_backward[161] = 12'd2594; rom_backward[162] = 12'd 863; rom_backward[163] = 12'd2466; rom_backward[164] = 12'd2768; rom_backward[165] = 12'd 561; rom_backward[166] = 12'd1230; rom_backward[167] = 12'd2099; 
rom_backward[168] = 12'd2572; rom_backward[169] = 12'd 757; rom_backward[170] = 12'd 556; rom_backward[171] = 12'd2773; rom_backward[172] = 12'd3010; rom_backward[173] = 12'd 319; rom_backward[174] = 12'd2266; rom_backward[175] = 12'd1063; 
rom_backward[176] = 12'd1684; rom_backward[177] = 12'd1645; rom_backward[178] = 12'd1239; rom_backward[179] = 12'd2090; rom_backward[180] = 12'd 780; rom_backward[181] = 12'd2549; rom_backward[182] = 12'd2954; rom_backward[183] = 12'd 375; 
rom_backward[184] = 12'd 109; rom_backward[185] = 12'd3220; rom_backward[186] = 12'd1292; rom_backward[187] = 12'd2037; rom_backward[188] = 12'd1031; rom_backward[189] = 12'd2298; rom_backward[190] = 12'd1745; rom_backward[191] = 12'd1584; 
rom_backward[192] = 12'd2688; rom_backward[193] = 12'd 641; rom_backward[194] = 12'd3061; rom_backward[195] = 12'd 268; rom_backward[196] = 12'd 992; rom_backward[197] = 12'd2337; rom_backward[198] = 12'd2596; rom_backward[199] = 12'd 733; 
rom_backward[200] = 12'd 941; rom_backward[201] = 12'd2388; rom_backward[202] = 12'd 892; rom_backward[203] = 12'd2437; rom_backward[204] = 12'd1021; rom_backward[205] = 12'd2308; rom_backward[206] = 12'd2390; rom_backward[207] = 12'd 939; 
rom_backward[208] = 12'd 642; rom_backward[209] = 12'd2687; rom_backward[210] = 12'd1868; rom_backward[211] = 12'd1461; rom_backward[212] = 12'd2377; rom_backward[213] = 12'd 952; rom_backward[214] = 12'd1482; rom_backward[215] = 12'd1847; 
rom_backward[216] = 12'd1540; rom_backward[217] = 12'd1789; rom_backward[218] = 12'd 540; rom_backward[219] = 12'd2789; rom_backward[220] = 12'd1678; rom_backward[221] = 12'd1651; rom_backward[222] = 12'd1626; rom_backward[223] = 12'd1703; 
rom_backward[224] = 12'd 279; rom_backward[225] = 12'd3050; rom_backward[226] = 12'd 314; rom_backward[227] = 12'd3015; rom_backward[228] = 12'd1173; rom_backward[229] = 12'd2156; rom_backward[230] = 12'd2573; rom_backward[231] = 12'd 756; 
rom_backward[232] = 12'd3096; rom_backward[233] = 12'd 233; rom_backward[234] = 12'd  48; rom_backward[235] = 12'd3281; rom_backward[236] = 12'd 667; rom_backward[237] = 12'd2662; rom_backward[238] = 12'd1920; rom_backward[239] = 12'd1409; 
rom_backward[240] = 12'd2229; rom_backward[241] = 12'd1100; rom_backward[242] = 12'd1041; rom_backward[243] = 12'd2288; rom_backward[244] = 12'd2606; rom_backward[245] = 12'd 723; rom_backward[246] = 12'd1692; rom_backward[247] = 12'd1637; 
rom_backward[248] = 12'd 680; rom_backward[249] = 12'd2649; rom_backward[250] = 12'd2746; rom_backward[251] = 12'd 583; rom_backward[252] = 12'd 568; rom_backward[253] = 12'd2761; rom_backward[254] = 12'd3312; rom_backward[255] = 12'd  17; 

        // PWM twiddles
rom_pwm[  0] = 12'd  17; rom_pwm[  1] = 12'd3312; rom_pwm[  2] = 12'd2761; rom_pwm[  3] = 12'd 568; rom_pwm[  4] = 12'd 583; rom_pwm[  5] = 12'd2746; rom_pwm[  6] = 12'd2649; rom_pwm[  7] = 12'd 680; 
rom_pwm[  8] = 12'd1637; rom_pwm[  9] = 12'd1692; rom_pwm[ 10] = 12'd 723; rom_pwm[ 11] = 12'd2606; rom_pwm[ 12] = 12'd2288; rom_pwm[ 13] = 12'd1041; rom_pwm[ 14] = 12'd1100; rom_pwm[ 15] = 12'd2229; 
rom_pwm[ 16] = 12'd1409; rom_pwm[ 17] = 12'd1920; rom_pwm[ 18] = 12'd2662; rom_pwm[ 19] = 12'd 667; rom_pwm[ 20] = 12'd3281; rom_pwm[ 21] = 12'd  48; rom_pwm[ 22] = 12'd 233; rom_pwm[ 23] = 12'd3096; 
rom_pwm[ 24] = 12'd 756; rom_pwm[ 25] = 12'd2573; rom_pwm[ 26] = 12'd2156; rom_pwm[ 27] = 12'd1173; rom_pwm[ 28] = 12'd3015; rom_pwm[ 29] = 12'd 314; rom_pwm[ 30] = 12'd3050; rom_pwm[ 31] = 12'd 279; 
rom_pwm[ 32] = 12'd1703; rom_pwm[ 33] = 12'd1626; rom_pwm[ 34] = 12'd1651; rom_pwm[ 35] = 12'd1678; rom_pwm[ 36] = 12'd2789; rom_pwm[ 37] = 12'd 540; rom_pwm[ 38] = 12'd1789; rom_pwm[ 39] = 12'd1540; 
rom_pwm[ 40] = 12'd1847; rom_pwm[ 41] = 12'd1482; rom_pwm[ 42] = 12'd 952; rom_pwm[ 43] = 12'd2377; rom_pwm[ 44] = 12'd1461; rom_pwm[ 45] = 12'd1868; rom_pwm[ 46] = 12'd2687; rom_pwm[ 47] = 12'd 642; 
rom_pwm[ 48] = 12'd 939; rom_pwm[ 49] = 12'd2390; rom_pwm[ 50] = 12'd2308; rom_pwm[ 51] = 12'd1021; rom_pwm[ 52] = 12'd2437; rom_pwm[ 53] = 12'd 892; rom_pwm[ 54] = 12'd2388; rom_pwm[ 55] = 12'd 941; 
rom_pwm[ 56] = 12'd 733; rom_pwm[ 57] = 12'd2596; rom_pwm[ 58] = 12'd2337; rom_pwm[ 59] = 12'd 992; rom_pwm[ 60] = 12'd 268; rom_pwm[ 61] = 12'd3061; rom_pwm[ 62] = 12'd 641; rom_pwm[ 63] = 12'd2688; 
rom_pwm[ 64] = 12'd1584; rom_pwm[ 65] = 12'd1745; rom_pwm[ 66] = 12'd2298; rom_pwm[ 67] = 12'd1031; rom_pwm[ 68] = 12'd2037; rom_pwm[ 69] = 12'd1292; rom_pwm[ 70] = 12'd3220; rom_pwm[ 71] = 12'd 109; 
rom_pwm[ 72] = 12'd 375; rom_pwm[ 73] = 12'd2954; rom_pwm[ 74] = 12'd2549; rom_pwm[ 75] = 12'd 780; rom_pwm[ 76] = 12'd2090; rom_pwm[ 77] = 12'd1239; rom_pwm[ 78] = 12'd1645; rom_pwm[ 79] = 12'd1684; 
rom_pwm[ 80] = 12'd1063; rom_pwm[ 81] = 12'd2266; rom_pwm[ 82] = 12'd 319; rom_pwm[ 83] = 12'd3010; rom_pwm[ 84] = 12'd2773; rom_pwm[ 85] = 12'd 556; rom_pwm[ 86] = 12'd 757; rom_pwm[ 87] = 12'd2572; 
rom_pwm[ 88] = 12'd2099; rom_pwm[ 89] = 12'd1230; rom_pwm[ 90] = 12'd 561; rom_pwm[ 91] = 12'd2768; rom_pwm[ 92] = 12'd2466; rom_pwm[ 93] = 12'd 863; rom_pwm[ 94] = 12'd2594; rom_pwm[ 95] = 12'd 735; 
rom_pwm[ 96] = 12'd2804; rom_pwm[ 97] = 12'd 525; rom_pwm[ 98] = 12'd1092; rom_pwm[ 99] = 12'd2237; rom_pwm[100] = 12'd 403; rom_pwm[101] = 12'd2926; rom_pwm[102] = 12'd1026; rom_pwm[103] = 12'd2303; 
rom_pwm[104] = 12'd1143; rom_pwm[105] = 12'd2186; rom_pwm[106] = 12'd2150; rom_pwm[107] = 12'd1179; rom_pwm[108] = 12'd2775; rom_pwm[109] = 12'd 554; rom_pwm[110] = 12'd 886; rom_pwm[111] = 12'd2443; 
rom_pwm[112] = 12'd1722; rom_pwm[113] = 12'd1607; rom_pwm[114] = 12'd1212; rom_pwm[115] = 12'd2117; rom_pwm[116] = 12'd1874; rom_pwm[117] = 12'd1455; rom_pwm[118] = 12'd1029; rom_pwm[119] = 12'd2300; 
rom_pwm[120] = 12'd2110; rom_pwm[121] = 12'd1219; rom_pwm[122] = 12'd2935; rom_pwm[123] = 12'd 394; rom_pwm[124] = 12'd 885; rom_pwm[125] = 12'd2444; rom_pwm[126] = 12'd2154; rom_pwm[127] = 12'd1175; 
    end
    
    // Read logic
    always @(posedge clk) begin
        data_forward  <= rom_forward[addr_forward];
        data_backward <= rom_backward[addr_backward];
        data_pwm      <= rom_pwm[addr_pwm];
    end

endmodule

// Constants for use in other modules
`define Q           12'd3329
`define INV_2       12'd1665
`define ZETA        12'd17
`define LOG_N       3'd8
